name: tformers
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - pip
  - tabulate
  - wikipedia
  - pip:
    - scikit-learn
    - tensorflow
    - transformers
    
    # Torch instead of TF
    # - torch
    # - torchvision
