name: tformers
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - tabulate
  - wikipedia
  - pip:
    - scikit-learn
    - transformers[torch]
    
    # Torch instead of TF
    # - torch
    # - torchvision
