name: tformers
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - tabulate
  - wikipedia
  - pip:
    - scikit-learn
    - sentence-transformers
    - tensorflow
    - transformers
    
    # Torch instead of TF
    # - torch
    # - torchvision
