name: transformers-qa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - beautifulsoup4
  - lxml
  - pip
  - tabulate
  - pip:
    - scikit-learn
    - tensorflow
    - transformers

    # requirements for `transformers` - https://github.com/huggingface/transformers/blob/master/examples/requirements.txt
    # - seqeval
    # - tensorboard
    # - tensorboardX
    
    # Torch instead of TF
    # - torch
    # - torchvision
